language: node_js
node_js:
- v10.14.2
branches:
  only:
  - master
install:
- git config --global user.email "cody.sehl+travis@gmail.com"
- git config --global user.name "Travis"
- npm install
script:
- ./travis/build.sh
- ./travis/commit.sh
after_success:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- git push -f https://github.com/lalunamel/codysehl.net.git gh-pages
env:
  global:
    secure: BjNgiU/+M1fGmH0DDsyU+kv1KuXoOuiXd7LjzyVGvO28lYRXgdZEpUPYtmKE+LYWZ6XD9W/vtBIOZp9/nGV3IaiKgheMRBZab8G1AmzcIF+PD62RBIcJFnooES2YZUmmJJ9wx2cCdbN/VV1UKZIsU1Pa/U6C+SPF+vIFAEAd8jM=
