language: node_js
node_js:
- 0.1
branches:
  only:
  - master
install:
- git config --global user.email "cody.sehl+travis@gmail.com"
- git config --global user.name "Travis"
- npm install
script:
- ./travis/build.sh
- ./travis/commit.sh
after_success:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- git push -f https://github.com/lalunamel/codysehl.net.git gh-pages
env:
  global:
    secure: OfeWWk5Shk507Up1aowPCMq/mtwMCyDwVH5CsqyUGnHptqnPNpKZcXHsKD7cl9AcBwa9Giz2Dh4hNJq0FBJxRjlWhAUvg17TFnOJ3yAkPwUQcMt0ZdPdpy4lRlsNzQLD3VjQeG6D9gw3ZBNYguYqBLgJqs6+HCiBDSRjOtmlP+s=
